title: "JCFP99"
lang_name: "Español"
other_projects_title: "Otros proyectos"
other_projects_description: "Otro tipo de proyectos hechos por trabajo, estudios o simplemente por hacer"
blog_title: "Reseñas de juegos"
blog_description: "Blog con cosas que pienso sobre algunos juegos"
games_title: "Mis juegos"
games_description: "Juego que he hecho o estoy intentando hacer"
tags_title: "Etiquetas"
date_months:
 - Enero
 - Febrero
 - Marzo
 - Abril
 - Mayo
 - Junio
 - Julio
 - Agosto
 - Septiembre
 - Octubre
 - Noviembre
 - Diciembre