title: "JCFP99"
lang_name: "English"
other_projects_title: "Other projects"
other_projects_description: "Non game projects from work, uni or just for fun"
blog_title: "Game reviews"
blog_description: "Kind of a blog with my thoughts about some games"
games_title: "My games"
games_description: "The games I've made or am trying to make"
tags_title: "Tags"
date_months:
 - January
 - February
 - March
 - April
 - May
 - June
 - July 
 - August
 - September
 - October
 - November
 - December